from __future__ import annotations

from decimal import Decimal, ROUND_HALF_UP


TICKS_PER_SECOND = 100


def to_tick(seconds: float) -> int:
    return int((Decimal(str(seconds)) * TICKS_PER_SECOND).quantize(Decimal("1"), rounding=ROUND_HALF_UP))


def phrase_pattern(phrase: dict) -> str:
    start_tick = to_tick(phrase["start_seconds"])
    end_tick = to_tick(phrase["end_seconds"])
    tokens: list[str] = []
    cursor = start_tick
    for event in phrase["events"]:
        event_start = max(cursor, to_tick(event["start_seconds"]))
        event_end = max(event_start + 1, to_tick(event["end_seconds"]))
        if event_start > cursor:
            tokens.append(_weighted("~", event_start - cursor))
        token = "~" if event["type"] == "rest" else str(int(event["midi"]))
        tokens.append(_weighted(token, event_end - event_start))
        cursor = event_end
    if cursor < end_tick:
        tokens.append(_weighted("~", end_tick - cursor))
    duration = max(1, end_tick - start_tick) / TICKS_PER_SECOND
    return f'note("{" ".join(tokens)}").slow({duration:.2f})'


def serialize_strudel(analysis: dict) -> str:
    phrases = analysis.get("phrases", [])
    lines = [
        "// Generated by Voice to Strudel. Numeric MIDI notes; one cycle = one second.",
        "setcpm(60)",
        "",
    ]
    for phrase in phrases:
        name = f"take{int(phrase['number'])}"
        lines.append(f"const {name} = {phrase_pattern(phrase)}")
    if phrases:
        lines.extend(["", "// Play one take at a time; change this final expression to audition another.", "take1"])
    else:
        lines.extend(["// No voiced phrases detected.", "silence"])
    return "\n".join(lines) + "\n"


def _weighted(token: str, weight: int) -> str:
    return token if weight == 1 else f"{token}@{weight}"

